name: Update GitHub Activity Chart

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download GitHub activity chart
        run: curl -o assets/img/Lyzev.svg https://ghchart.rshah.org/Lyzev
      - uses: stefanzweifel/git-auto-commit-action@v5